### ISSUE TITLE
Good job with implementing AEGIS!

### ISSUE THREAD

**Issue by jedisct1** [sayantn/crypto-rust#1]
Hi,

And congrats for having implemented all the AEGIS variants in Rust!

I'm working on the draft that it seems your implementation has been using as a reference.

We'd like to make this document as clear and useful as possible for developers, so your input would be very valuable.

How difficult was it for you to write this implementation using that document?

Is there anything you found confusing or that was missing?

Thanks for your feedback!

**Comment by sayantn** [comment]
I am guessing that you are referring to the IETF draft. I used that to implement AEGIS128X and AEGIS256X. It was absolutely a breeze to follow through. I reused most of the code from the serial AEGIS variants. The draft is excellently and (more importantly) clearly written. The test vectors at the end also helped a lot.

**Comment by jedisct1** [comment]
Thanks for your feedback. Glad to hear that you had no issues writing an implementation. The RGLC for the document is going to happen soon, after which it will be difficult to make updates. So we want to make sure that implementers are happy with it.
Thanks!

**Comment by jedisct1** [comment]
Hi Sayantan,

I hope you’re doing well.

As you know, standardization processes can be quite slow and bureaucratic, but I wanted to let you know that the AEGIS draft has made some progress by successfully passing the CFRG panel review.

The next step will be the final community call (RGLC), where members of the CFRG mailing list can provide their feedback and help determine whether the document should be published as an RFC.

Since you've implemented AEGIS based on this document, it would be incredibly helpful if you could share your thoughts on the list after the RGLC is announced. Of course, there’s no obligation at all—only if you feel inclined.

Kind regards,
-Frank.

**Comment by sayantn** [comment]
For sure. Where can I register for the CFRG mailing list?

**Comment by jedisct1** [comment]
Thank you so much!

Here's the information page about the CFRG mailing list: https://www.irtf.org/cfrg.html

But no need to hurry. The RGLC is only going to be announced after the end of the forthcoming IETF meeting, so after November 8.

**Comment by jedisct1** [comment]
Hi Sayantan!

The RGLC was just announced today!

**Comment by sayantn** [comment]
Thanks for letting me know. I will certainly look into the RGLC

**Comment by sayantn** [comment]
@jedisct1 Congratulations on the RGLC being successful 🥰

**Comment by jedisct1** [comment]
Thank you for your support!
